name: flutter_template
description: Starter template
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_dotenv: ^6.0.0
  # supabase_flutter removed in favor of Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  google_mobile_ads: ^6.0.0
  flex_color_scheme: ^8.2.0
  shared_preferences: ^2.3.2
  go_router: ^14.2.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - .env.development
    - .env.staging
    - .env.production
    - assets/app_icon.png

# Launcher icon generation
flutter_launcher_icons:
  # Generate a single icon used for all platforms by default
  image_path: assets/app_icon.png
  android: true
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21
  adaptive_icon_foreground: assets/app_icon.png
  adaptive_icon_background: "#FFFFFF"
  # Optional: if you want per-flavor icons, uncomment and point all to the same image (or different ones)
  # flavors:
  #   production:
  #     image_path: assets/app_icon.png
  #     android: true
  #     ios: true
  #   staging:
  #     image_path: assets/app_icon.png
  #     android: true
  #     ios: true
  #   development:
  #     image_path: assets/app_icon.png
  #     android: true
  #     ios: true
